apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wakapi.fullname" . }}-secrets
  labels:
    {{- include "wakapi.labels" . | nindent 4 }}
type: Opaque
data:
  WAKAPI_DB_PASSWORD: {{ .Values.wakapi_secrets.db.password | b64enc | quote }}
  WAKAPI_PASSWORD_SALT: {{ .Values.wakapi_secrets.security.password_salt | b64enc | quote }}
  WAKAPI_MAIL_SMTP_PASS: {{ .Values.wakapi_secrets.mail.smtp.password | b64enc | quote }}